# Generated by Django 4.2.7 on 2023-11-25 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100, verbose_name='User First Name')),
                ('lastName', models.CharField(max_length=100, verbose_name='User Last Name')),
                ('email', models.EmailField(max_length=100, verbose_name='User Email Adress')),
                ('phone', models.CharField(max_length=100, verbose_name='User Phone Number')),
                ('message', models.TextField(blank=True, verbose_name='User Message')),
            ],
        ),
    ]
