# Generated by Django 4.2.7 on 2023-11-16 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Kurs Adı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Kurs Açıklaması')),
                ('image', models.ImageField(default='courses/default.jpg', upload_to='courses/%Y/%m/%d/', verbose_name='Kurs Fotoğrafı')),
                ('date', models.DateTimeField(auto_now=True)),
                ('avaliable', models.BooleanField(default=True, verbose_name='Kursu Yayına Al')),
            ],
        ),
    ]
