# Generated by Django 4.2.7 on 2023-11-21 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
        ('courses', '0005_rename_categoryname_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teachers.teacher'),
        ),
        migrations.AlterField(
            model_name='course',
            name='avaliable',
            field=models.BooleanField(default=True, verbose_name='Course Avaliable'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Course Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(default='courses/default.jpg', upload_to='courses/%Y/%m/%d/', verbose_name='Course Image'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Course Name'),
        ),
    ]
